name: App Build & Deploy

on:
  # When PRs are merged, the push event is triggered for the target branch.
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew build
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY_PROD}}
        run: heroku container:login
      - name: Push image to registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY_PROD}}
        run: heroku container:push -a ${{secrets.HEROKU_APP_NAME_PROD}} web
      - name: Release
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY_PROD}}
        run: heroku container:release -a ${{secrets.HEROKU_APP_NAME_PROD}} web