name: App Build & Deploy

#disabling auto deploy, as heroku has ended free tier
on: workflow_dispatch
  # When PRs are merged, the push event is triggered for the target branch.
  # push:
  #   branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew build
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    environment: 
      name: Demo
      url: https://invoice-service-vrdemo.herokuapp.com/swagger-ui.html
    needs: build

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_PROD}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_DEMO}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
